# Generated by Django 5.2.8 on 2025-11-10 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiltutor',
            name='sobrenombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sobrenombre'),
        ),
        migrations.AlterField(
            model_name='perfiltutor',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
    ]
