# Generated by Django 5.2.8 on 2025-11-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_mascota_pesomascota'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='microchip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
