# Generated by Django 5.2.8 on 2025-11-10 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_mascota_microchip'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitaVeterinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateField()),
                ('motivo', models.CharField(max_length=255)),
                ('tiene_alergias', models.BooleanField(default=False)),
                ('detalle_alergias', models.TextField(blank=True, null=True)),
                ('tratamiento', models.TextField(blank=True, null=True)),
                ('notas_adicionales', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_veterinarias', to='registro.mascota')),
            ],
            options={
                'verbose_name': 'Visita Veterinaria',
                'verbose_name_plural': 'Visitas Veterinarias',
                'ordering': ['-fecha_visita'],
            },
        ),
    ]
