# Generated by Django 5.2.8 on 2025-11-10 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_visitaveterinaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergias', models.TextField(blank=True, null=True)),
                ('esterilizado', models.BooleanField(default=False)),
                ('microchip', models.CharField(blank=True, max_length=100, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('mascota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_clinica', to='registro.mascota')),
            ],
            options={
                'verbose_name': 'Ficha Clínica',
                'verbose_name_plural': 'Fichas Clínicas',
            },
        ),
        migrations.CreateModel(
            name='EventoClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evento', models.DateField()),
                ('tipo_evento', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('veterinario', models.CharField(blank=True, max_length=150, null=True)),
                ('medicacion', models.TextField(blank=True, null=True)),
                ('proximos_eventos', models.TextField(blank=True, null=True)),
                ('consideraciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('ficha_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='registro.fichaclinica')),
            ],
            options={
                'verbose_name': 'Evento Clínico',
                'verbose_name_plural': 'Eventos Clínicos',
                'ordering': ['-fecha_evento'],
            },
        ),
        migrations.DeleteModel(
            name='VisitaVeterinaria',
        ),
    ]
