# Generated by Django 5.2.8 on 2025-11-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_fichaclinica_eventoclinico_delete_visitaveterinaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaclinica',
            name='condiciones_cronicas',
            field=models.TextField(blank=True, null=True, verbose_name='Condiciones Crónicas'),
        ),
        migrations.AddField(
            model_name='fichaclinica',
            name='frecuencia_cardiaca',
            field=models.IntegerField(blank=True, null=True, verbose_name='Frecuencia Cardíaca (lpm)'),
        ),
        migrations.AddField(
            model_name='fichaclinica',
            name='historial_enfermedades',
            field=models.TextField(blank=True, null=True, verbose_name='Historial de Enfermedades'),
        ),
        migrations.AddField(
            model_name='fichaclinica',
            name='medicamentos_actuales',
            field=models.TextField(blank=True, null=True, verbose_name='Medicamentos Actuales'),
        ),
        migrations.AddField(
            model_name='fichaclinica',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AddField(
            model_name='fichaclinica',
            name='proxima_cita',
            field=models.DateField(blank=True, null=True, verbose_name='Próxima Cita'),
        ),
        migrations.AddField(
            model_name='fichaclinica',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Temperatura (°C)'),
        ),
        migrations.AddField(
            model_name='fichaclinica',
            name='tipo_sangre',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('DEA1.1+', 'DEA1.1+'), ('DEA1.1-', 'DEA1.1-'), ('DEA1.2+', 'DEA1.2+'), ('DEA1.2-', 'DEA1.2-')], max_length=10, null=True, verbose_name='Tipo de Sangre'),
        ),
        migrations.AddField(
            model_name='fichaclinica',
            name='ultima_visita',
            field=models.DateField(blank=True, null=True, verbose_name='Última Visita'),
        ),
        migrations.AddField(
            model_name='fichaclinica',
            name='vacunas_al_dia',
            field=models.BooleanField(default=False, verbose_name='Vacunas al Día'),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='comentarios',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarios Adicionales'),
        ),
    ]
