# Generated by Django 5.2.8 on 2025-11-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0007_fichaclinica_condiciones_cronicas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoclinico',
            name='tipo_evento',
            field=models.CharField(choices=[('cita_general', 'Cita General'), ('cita_especialista', 'Cita Especialista'), ('medicacion', 'Medicación'), ('curacion', 'Curación'), ('vacuna', 'Vacuna'), ('desparasitacion', 'Desparasitación'), ('comentario', 'Comentario')], default='comentario', max_length=50),
        ),
    ]
