# Generated by Django 5.2.8 on 2025-11-15 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0009_mascota_activa'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialFichaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sangre', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('DEA1.1+', 'DEA1.1+'), ('DEA1.1-', 'DEA1.1-'), ('DEA1.2+', 'DEA1.2+'), ('DEA1.2-', 'DEA1.2-')], max_length=10, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('esterilizado', models.BooleanField(default=False)),
                ('vacunas_al_dia', models.BooleanField(default=False)),
                ('vacuna_nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('vacuna_fecha', models.DateField(blank=True, null=True)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('condiciones_cronicas', models.TextField(blank=True, null=True)),
                ('medicamentos_actuales', models.TextField(blank=True, null=True)),
                ('historial_enfermedades', models.TextField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ficha_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_registros', to='registro.fichaclinica')),
            ],
            options={
                'verbose_name': 'Registro Histórico',
                'verbose_name_plural': 'Registros Históricos',
                'ordering': ['-creado_en'],
            },
        ),
    ]
