# Generated by Django 5.2.8 on 2025-11-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0010_historialfichaclinica'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='esterilizado',
            field=models.BooleanField(default=False, verbose_name='Esterilizado'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='sexo',
            field=models.CharField(blank=True, choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=10, null=True, verbose_name='Sexo'),
        ),
    ]
