# Generated by Django 5.2.8 on 2025-11-22 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0011_mascota_esterilizado_mascota_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoclinico',
            name='diagnostico',
            field=models.TextField(blank=True, null=True, verbose_name='Diagnóstico'),
        ),
        migrations.CreateModel(
            name='ArchivoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del archivo')),
                ('archivo', models.FileField(upload_to='archivos_eventos/%Y/%m/%d/', verbose_name='Archivo')),
                ('tipo_archivo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de archivo')),
                ('tamano', models.BigIntegerField(verbose_name='Tamaño (bytes)')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('evento_clinico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_adjuntos', to='registro.eventoclinico')),
            ],
            options={
                'verbose_name': 'Archivo Adjunto',
                'verbose_name_plural': 'Archivos Adjuntos',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
