# Generated by Django 5.2.8 on 2025-11-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0013_perfiltutor_calle_numero_comuna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfiltutor',
            name='direccion',
        ),
        migrations.AddField(
            model_name='eventoclinico',
            name='hora_evento',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora del evento'),
        ),
    ]
