# Generated by Django 5.2.8 on 2025-11-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0014_remove_perfiltutor_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiltutor',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles_tutores/', verbose_name='Foto de Perfil'),
        ),
    ]
