# Generated by Django 5.2.8 on 2025-11-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0015_perfiltutor_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='mascotas/', verbose_name='Foto de la Mascota'),
        ),
    ]
